//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaInformacionPersonal.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public int ID_USUARIO { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public Nullable<int> DUI { get; set; }
        public Nullable<int> TELEFONO { get; set; }
        public string DIRECCION { get; set; }
        public string NIVEL_EDUCATIVO { get; set; }
        public Nullable<int> ANIOS_EXPERIENCIA { get; set; }
        public string PLAZA_ACTUAL { get; set; }
        public Nullable<int> ID_SESION { get; set; }
        public Nullable<int> ID_CURRICULUM { get; set; }
    
        public virtual CURRICULUMS CURRICULUMS { get; set; }
        public virtual SESIONES SESIONES { get; set; }
    }
}
